### ISSUE TITLE
No .env.example file

### ISSUE THREAD

**Issue by VictorAlagwu** [princenazi/anaklestores#1]
Following your instructions, there is .env.example file missing in the folder.

What are the possible the parameters that are available in the file, so i can create it on my end.

Thanks

**Comment by princenazi** [comment]
I am really sorry about that, i just uploaded one. You can take a look at it

**Comment by VictorAlagwu** [comment]
Cool, wish you success as you go for your next interview. Once apply but never make it through the second interview
